# Generated by Django 5.0.1 on 2024-05-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='tag_id',
            field=models.CharField(max_length=50),
        ),
    ]
