# Generated by Django 5.0.1 on 2024-05-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_userenrolled_tag_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
