# Generated by Django 5.0.1 on 2024-05-15 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_sign_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userenrolled',
            name='facial_data',
        ),
        migrations.CreateModel(
            name='FacialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facial_data', models.ImageField(upload_to='facial_data/', verbose_name='Facial Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_images', to='app1.userenrolled')),
            ],
        ),
    ]
