# Generated by Django 5.0.1 on 2024-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_preshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='preshift/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
