# Generated by Django 5.0.1 on 2024-05-21 11:23

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_toolbox_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='facial_data',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.user_image_upload_path, verbose_name='Facial Data'),
        ),
    ]
