# Generated by Django 5.0.1 on 2024-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_userenrolled_facial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
