# Generated by Django 5.0.1 on 2024-05-22 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_userenrolled_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientation',
            name='attachments',
            field=models.FileField(upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
