# Generated by Django 5.0.1 on 2024-05-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_userenrolled_my_comply'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
