# Generated by Django 5.0.1 on 2024-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_onsiteuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='facial_data',
            field=models.TextField(blank=True, null=True, verbose_name='Facial Data'),
        ),
    ]
