# Generated by Django 5.0.1 on 2024-06-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_userenrolled_facial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='site_pictures/'),
        ),
    ]
