# Generated by Django 5.0.1 on 2024-06-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_site_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
