# Generated by Django 5.0.1 on 2024-06-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
