# Generated by Django 5.0.1 on 2024-06-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_asset_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/'),
        ),
    ]
