# Generated by Django 5.0.1 on 2024-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_userenrolled_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='job_role',
            field=models.CharField(max_length=100),
        ),
    ]
