# Generated by Django 5.0.1 on 2024-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_userenrolled_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100),
        ),
    ]
