# Generated by Django 5.0.1 on 2024-07-21 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_asset_site_userenrolled_site_alter_asset_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrolled',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
