# Generated by Django 5.0.1 on 2024-07-21 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_userenrolled_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.site'),
        ),
    ]
