# Generated by Django 5.0.1 on 2024-07-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_userenrolled_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sites',
            field=models.ManyToManyField(blank=True, to='app1.site'),
        ),
    ]
