# Generated by Django 5.0.1 on 2024-07-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_customuser_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteuser',
            name='site',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preshift',
            name='site',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolbox',
            name='site',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.site'),
            preserve_default=False,
        ),
    ]
