# Generated by Django 5.0.1 on 2024-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_onsiteuser_site_preshift_site_toolbox_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolled',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
