# Generated by Django 5.0.1 on 2024-07-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_userenrolled_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='site',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnstile_s',
            name='site',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.site'),
            preserve_default=False,
        ),
    ]
