# Generated by Django 5.0.1 on 2024-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_updatestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateStatus',
        ),
        migrations.AddField(
            model_name='turnstile_s',
            name='unlock',
            field=models.BooleanField(default=False),
        ),
    ]
