# Generated by Django 5.0.1 on 2024-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_updatestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpdateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False)),
            ],
        ),
    ]
