# Generated by Django 5.0.1 on 2024-08-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_datasetupdateflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetUpdateFlag',
        ),
    ]
