# Generated by Django 5.0.1 on 2024-08-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_folderstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteuser',
            name='face',
            field=models.BooleanField(default=False),
        ),
    ]
