# Generated by Django 5.0.1 on 2024-08-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_onsiteuser_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_id',
        ),
    ]
