# Generated by Django 5.0.1 on 2024-08-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_remove_asset_asset_category_remove_asset_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
